# Generated by Django 2.1.4 on 2018-12-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layouts.Section')),
            ],
        ),
        migrations.AddField(
            model_name='layout',
            name='sections',
            field=models.ManyToManyField(through='layouts.LayoutSection', to='layouts.Section'),
        ),
    ]
