# Generated by Django 2.1.4 on 2018-12-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0004_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layoutsection',
            unique_together={('layout', 'priority')},
        ),
    ]
