# Generated by Django 2.1.4 on 2018-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0005_auto_20181204_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsection',
            name='priority',
            field=models.PositiveIntegerField(),
        ),
    ]
